"""Phase 2: re-score sentence-reordered CoTs through the trained model.

We reuse the exact recorded evaluation generations. For each scenario we take
the model's own chain of thought, apply a structural intervention, feed the
modified CoT back into the same model with the exact training format
(``<prompt> <cot>\\nFinal answer:``), and read off a single greedy label for
the whole thing.

The output is written in the SAME schema as the original evaluation dataset
(``index, prompt, chain_of_thought, raw_generation, prediction, gold,
correct``) so it is a drop-in for the existing analysis and plotting code. The
``chain_of_thought`` field holds the modified CoT that was actually scored.

Interventions:
  * ``control``            - feed the original CoT back unchanged (sanity check).
  * ``swap_first_two``     - swap sentence 1 and sentence 2 (the "1-2 flip"): the
                             original second sentence becomes the first sentence.
  * ``paraphrase_s1``      - replace sentence 1 with a stance-preserving
                             paraphrase, keeping it in position 1. If the label
                             is unchanged, the rule keys on the *meaning* of
                             sentence 1, not its literal wording.
  * ``paraphrase_s1_swap`` - paraphrase sentence 1 AND move it to position 2.
  * ``full_paraphrase``    - replace the entire CoT with a full paraphrase
                             that preserves the original moral pattern.
  * ``full_negation``      - replace the entire CoT with a fully negated /
                             inverted version generated by paraphrase_cot.py.

The paraphrase modes read the paraphrases produced by ``paraphrase_cot.py``.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import torch
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

from cot_utils import clean_chain_of_thought, split_sentences


LABEL_RE = re.compile(r"[01]")
TEXT_ANSWER_RE = re.compile(
    r"\b(final answer|answer|label)\s*[:\-]\s*(yes|no|true|false)\b", re.IGNORECASE
)


DTYPES = {
    "float32": torch.float32,
    "float16": torch.float16,
    "bfloat16": torch.bfloat16,
}


def inference_device(dtype_arg: str, device_arg: str) -> tuple[str, torch.dtype]:
    if device_arg == "cpu":
        return "cpu", DTYPES.get(dtype_arg, torch.float32)
    if device_arg == "cuda" or (device_arg == "auto" and torch.cuda.is_available()):
        return "cuda", DTYPES.get(dtype_arg, torch.float16)
    if device_arg == "mps" or (device_arg == "auto" and torch.backends.mps.is_available()):
        return "mps", DTYPES.get(dtype_arg, torch.float32)
    return "cpu", DTYPES.get(dtype_arg, torch.float32)


def parse_boolq_label(text: str) -> int | None:
    text_matches = list(TEXT_ANSWER_RE.finditer(text))
    if text_matches:
        answer = text_matches[-1].group(2).lower()
        return 1 if answer in ("yes", "true") else 0
    low = text.lower().strip()
    final_line = re.search(r"(?:final answer|answer|label)\s*[:\-]\s*(.*)$", low, re.DOTALL)
    if final_line:
        answer_text = final_line.group(1)
        if re.search(r"\b(yes|true|correct)\b", answer_text):
            return 1
        if re.search(r"\b(no|false|incorrect)\b", answer_text):
            return 0
    if re.search(r"\b(yes|true|correct)\b", low) and not re.search(r"\b(no|false|incorrect)\b", low):
        return 1
    if re.search(r"\b(no|false|incorrect)\b", low) and not re.search(r"\b(yes|true|correct)\b", low):
        return 0
    return None


def parse_label(text: str, task: str) -> int | None:
    if task == "boolq":
        parsed = parse_boolq_label(text)
        if parsed is not None:
            return parsed
    match = LABEL_RE.search(text)
    return int(match.group(0)) if match else None


def load_records(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def load_completed(path: Path) -> set[int]:
    if not path.exists():
        return set()
    done: set[int] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            done.add(int(json.loads(line)["index"]))
    return done


def load_paraphrases(path: str | None) -> dict[int, str]:
    records = load_paraphrase_records(path)
    return {
        index: (record.get("paraphrase") or "").strip()
        for index, record in records.items()
        if (record.get("paraphrase") or "").strip()
    }


def load_paraphrase_records(path: str | None) -> dict[int, dict]:
    if not path or not Path(path).exists():
        return {}
    mapping: dict[int, dict] = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if line.strip():
            record = json.loads(line)
            mapping[int(record["index"])] = record
    return mapping


def apply_intervention(
    sentences: list[str], mode: str, paraphrase: str | None
) -> list[str] | None:
    """Return the modified sentences, or None if the intervention does not apply."""
    if mode == "control":
        return list(sentences)
    if mode == "swap_first_two":
        if len(sentences) < 2:
            return None
        reordered = list(sentences)
        reordered[0], reordered[1] = reordered[1], reordered[0]
        return reordered
    if mode in ("full_paraphrase", "full_negation"):
        if not paraphrase:
            return None
        rewritten = split_sentences(paraphrase)
        return rewritten if rewritten else [paraphrase]
    if mode in ("paraphrase_s1", "paraphrase_s1_swap", "negate_s1"):
        if not sentences or not paraphrase:
            return None
        modified = list(sentences)
        modified[0] = paraphrase
        if mode == "paraphrase_s1_swap":
            if len(modified) < 2:
                return None
            modified[0], modified[1] = modified[1], modified[0]
        return modified
    raise ValueError(f"unknown intervention: {mode}")


@torch.no_grad()
def score_label(
    model, tokenizer, prompt: str, chain_of_thought: str, max_new_tokens: int, *, task: str
) -> tuple[int | None, str]:
    """Teacher-force a CoT and greedily read off the final-answer label."""
    text = f"{prompt} {chain_of_thought}\nFinal answer:"
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    output_ids = model.generate(
        **inputs,
        do_sample=False,
        max_new_tokens=max_new_tokens,
        pad_token_id=tokenizer.eos_token_id,
        temperature=None,
        top_p=None,
        top_k=None,
    )
    generated = tokenizer.decode(
        output_ids[0, inputs["input_ids"].shape[-1] :], skip_special_tokens=True
    ).strip()
    return parse_label(generated, task), generated


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Re-score sentence-reordered CoTs through the trained model."
    )
    parser.add_argument(
        "--model",
        default="checkpoints/qwen-cot-sft",
        help="Model (or LoRA adapter dir) whose first-sentence rule we probe.",
    )
    parser.add_argument(
        "--generations",
        default="data/evaluation_data/qwen/ETHICS/qwen05b_v1.jsonl",
        help="Recorded evaluation generations to intervene on.",
    )
    parser.add_argument(
        "--intervention",
        default="swap_first_two",
        choices=[
            "control",
            "swap_first_two",
            "paraphrase_s1",
            "paraphrase_s1_swap",
            "negate_s1",
            "full_paraphrase",
            "full_negation",
        ],
    )
    parser.add_argument(
        "--paraphrases",
        default="data/intervention_data/qwen/ETHICS/interventions/paraphrased_cot.jsonl",
        help="Rewritten first sentences from paraphrase_cot.py (paraphrase/negate modes).",
    )
    parser.add_argument(
        "--output",
        default="data/intervention_data/qwen/ETHICS/qwen05b_v1_swap12.jsonl",
    )
    parser.add_argument("--max-new-tokens", type=int, default=8)
    parser.add_argument("--limit", type=int, default=0, help="0 = all records.")
    parser.add_argument(
        "--task",
        choices=["ethics", "boolq", "sbic"],
        default="ethics",
        help="Label parser for the final-answer token (boolq accepts yes/no).",
    )
    parser.add_argument(
        "--device",
        choices=["auto", "cpu", "mps", "cuda"],
        default="auto",
        help="Use 'cpu' on Apple Silicon if MPS garbles generation.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Re-score all records even if already present in the output file.",
    )
    parser.add_argument(
        "--dtype",
        choices=["auto", "float32", "float16", "bfloat16"],
        default="auto",
        help="Inference dtype. On CPU/MPS, auto uses float32 for stable generation.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    records = load_records(Path(args.generations))
    if args.limit:
        records = records[: args.limit]

    needs_rewrites = args.intervention in (
        "paraphrase_s1",
        "paraphrase_s1_swap",
        "negate_s1",
        "full_paraphrase",
        "full_negation",
    )
    paraphrases = load_paraphrases(args.paraphrases) if needs_rewrites else {}
    paraphrase_records = load_paraphrase_records(args.paraphrases) if needs_rewrites else {}
    if needs_rewrites and not paraphrases:
        raise SystemExit(
            f"No rewritten sentences found at {args.paraphrases}. "
            "Run intervention/paraphrase_cot.py (with --mode negate for negation) first."
        )

    device, dtype = inference_device(args.dtype, args.device)
    print(f"task={args.task} inference device: {device} dtype={dtype}")

    tokenizer = AutoTokenizer.from_pretrained(args.model)
    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        torch_dtype=dtype,
        device_map="auto" if device == "cuda" else None,
    )
    if device in ("mps", "cpu"):
        model.to(device)
    model.eval()

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if args.overwrite and output_path.exists():
        output_path.unlink()
    completed = load_completed(output_path)

    correct = 0
    parsed = 0
    applied = 0
    skipped = 0

    with output_path.open("a", encoding="utf-8") as output_file:
        for record in tqdm(records, desc=args.intervention):
            index = int(record["index"])
            if index in completed:
                skipped += 1
                continue
            prompt = record["prompt"]
            gold = int(record["gold"])
            original_prediction = record.get("prediction")
            cot_clean = clean_chain_of_thought(record.get("chain_of_thought", ""))
            sentences = split_sentences(cot_clean)

            paraphrase = paraphrases.get(index)
            reordered = apply_intervention(
                sentences, args.intervention, paraphrase
            )
            s1_flipped = (
                args.intervention == "negate_s1"
                and paraphrase is not None
                and reordered is not None
            )
            intervention_applied = reordered is not None and (
                args.intervention != "negate_s1" or paraphrase is not None
            )
            if reordered is None:
                reordered = sentences if sentences else [cot_clean]
            else:
                applied += 1

            chain_of_thought = " ".join(reordered)
            prediction, model_output = score_label(
                model, tokenizer, prompt, chain_of_thought, args.max_new_tokens, task=args.task
            )

            if prediction is not None:
                parsed += 1
                correct += int(prediction == gold)

            flip_meta = paraphrase_records.get(index, {})
            output_file.write(
                json.dumps(
                    {
                        "index": index,
                        "prompt": prompt,
                        "chain_of_thought": chain_of_thought,
                        "raw_generation": f"{chain_of_thought}\nFinal answer:{model_output}",
                        "model_output": model_output,
                        "prediction": prediction,
                        "gold": gold,
                        "correct": prediction == gold if prediction is not None else None,
                        "intervention": args.intervention,
                        "intervention_applied": intervention_applied,
                        "s1_flipped": s1_flipped,
                        "original_prediction": original_prediction,
                        "original_stance": flip_meta.get("original_stance"),
                        "paraphrase_stance": flip_meta.get("paraphrase_stance"),
                        "negate_against": flip_meta.get("negate_against"),
                        "s1_stance": flip_meta.get("s1_stance"),
                        "full_cot_stance": flip_meta.get("full_cot_stance"),
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )
            output_file.flush()

    n = len(records)
    print(f"intervention={args.intervention}")
    print(f"n={n} skipped={skipped} intervention_applied={applied}")
    print(f"accuracy_vs_gold={correct / n if n else 0.0:.3f}")
    print(f"parse_rate={parsed / n if n else 0.0:.3f}")
    print(f"wrote {output_path}")


if __name__ == "__main__":
    main()
